# Generated by Django 3.2.2 on 2021-12-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.CharField(max_length=250),
        ),
    ]
