# Generated by Django 3.2.9 on 2021-12-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
