# Generated by Django 3.2.9 on 2021-12-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'managed': False},
        ),
    ]
