# Generated by Django 3.2.9 on 2021-12-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_image_link'),
        ('cars', '0004_alter_car_options'),
    ]

    operations = [
    ]
