# Generated by Django 3.2.9 on 2021-12-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20211208_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'managed': True},
        ),
    ]
