# Generated by Django 3.2.9 on 2021-12-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_main_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.CharField(max_length=150),
        ),
    ]
