# Generated by Django 3.2.9 on 2021-12-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20211208_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'managed': True},
        ),
    ]
