# Generated by Django 3.2.9 on 2021-12-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_img',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
