# Generated by Django 3.2.9 on 2021-12-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_main_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='car_comment',
        ),
        migrations.AlterModelTable(
            name='image',
            table='car_image',
        ),
    ]
